name: prediccio_ms_patates
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # Ciència de dades i ML
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  
  # Visualització
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # Utilitats
  - jupyter
  - notebook
  - ipykernel>=6.29
  - ipywidgets
  - typing_extensions>=4.8
  
  # Pip packages (si es necessita alguna cosa extra)
  - pip
  - pip:
    # TensorFlow i Keras
    - tensorflow==2.13.0
    - protobuf==3.20.3  # Per compatibilitat amb TensorFlow