name: ms_patates_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10

  # CUDA + cuDNN per TensorFlow 2.10 en Windows
  - cudatoolkit=11.2
  - cudnn=8.1.0

  # Ciència de dades i ML
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0

  # Visualització
  - matplotlib=3.7.2
  - seaborn=0.12.2

  # Jupyter
  - jupyter=1.0.0
  - ipykernel=6.25.0

  # Pip packages
  - pip
  - pip:
      - tensorflow==2.10.0
      - typing_extensions>=4.4